# Generated by Django 5.1.4 on 2025-01-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='state_about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_pics', models.ImageField(upload_to='imags')),
                ('state_name', models.CharField(max_length=50)),
            ],
        ),
    ]
