# Generated by Django 5.1.4 on 2025-01-15 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details_all', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='city_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('city_pics01', models.ImageField(upload_to='city_pics')),
                ('city_pics02', models.ImageField(upload_to='city_pics')),
                ('city_pics03', models.ImageField(upload_to='city_pics')),
                ('city_pics04', models.ImageField(upload_to='city_pics')),
                ('city_description', models.TextField()),
                ('state_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Details_all.state_about')),
            ],
        ),
    ]
